{
 "title": "QuakeWatch Project Dashboard Copy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QuakeWatch CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"quakewatch-helm\",pod=~\"quakewatch.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QuakeWatch Pod Down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"quakewatch-helm\",pod=~\"quakewatch.*\",phase=~\"Pending|Unknown|Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QuakeWatch pod restart count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"quakewatch-helm\"}[5m])) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QuakeWatch Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"quakewatch-helm\",pod=~\"quakewatch.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QuakeWatch Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"quakewatch-helm\",pod=~\"quakewatch.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}