apiVersion: v1
kind: Service
metadata:
  name: hello-flask
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: hello-flask
spec:
  type: NodePort
  selector:
    app: hello-flask
  ports:
  - name: http
    port: 5000
    targetPort: 5000
